services:
  nanos-world-server:
    image: olivatooo/nanos-world-server:latest
    container_name: nanos-world-server
    restart: unless-stopped
    # Uncomment to always have the latest version
    # pull_policy: always
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
    volumes:
      - ./Packages:/app/Packages
      - ./Assets:/app/Assets
      # You can create a Config.toml file to configure the server
      # - ./Config.toml:/app/Config.toml
    # Uncomment and modify to pass parameters to the server
    # command: ["--port", "7777", "--map", "MyMap"]
